version: '3.8'

services:
  ecommerceDB:
    image: postgres:15.3
    container_name: ecommerce-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - 5432:5432
volumes:
  postgres:
